baseurl: ""
url: "http://example.org"

plugins:
   - jekyll-rdf

# Jekyll RDF settings
jekyll_rdf:
    path: "_data/vocabolangelo.ttl"
    default_template: "default"
    class_template_mappings:
        "http://www.w3.org/2004/02/skos/core#Concept": "concept"
        "http://xmlns.com/foaf/0.1/Person": "person"
